### ISSUE TITLE
Capstone Project: Review

### ISSUE THREAD

**Issue by RiyaBulia12** [tarikbouari/AfroTech-Festival#3]
# Hello @tarikbouari  👋 , 

Congratulations! Good job so far!  🎉  I know you've been very diligent and committed to implementing this project, and we, as a team, appreciate the effort you put in! But there are some issues that you still need to work on in this project but you are almost there! 

![so-close](https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

### Suggested Changes ♻️
- There are some commented lines in your CSS file. Please make sure to not commit any commented code on your project😃 
- Some of your CSS and JS files are on the root folder we suggest you put the files in their respective folders for better file structure.
- It would be great if you could also add some interaction like hovering on the cards in the Main Program section to give it a more dramatic style. 
- Some of the Images in the Featured Speaker section look more stretchy than others. We recommend using the `background-size` property to fix the size of the image;
<img width="1288" alt="Screenshot 2022-07-29 at 1 48 23 PM" src="https://user-images.githubusercontent.com/24832846/181716140-866ba9da-5142-4bb5-9cfc-38cb60e35762.png">

 
Cheers and Happy coding!👏👏👏 💻 

Please feel free to reach out or leave any questions or comments on the issue if you find anything unclear

**Comment by tarikbouari** [comment]
# Hello, dear teammate 👋  

Thank you for your feedback, I really appreciate the effort you put into this. 
I will implement the suggested changes and refactor my code.

 Thank you for your time and Happy coding  🥳 👏 💻 .
